### PR TITLE
Add support for ARM

### LINKED ISSUE #4: Add Apple M1/osx-arm64?
### Comment:

Hello! Thanks for adding this feed. This issue is just to ask if the `osx-arm64` platform can be added to the list.

### PR DESCRIPTION
**Pull request by giswqs**

### CODE REVIEW

**Comment by giswqs** [comment]
@conda-forge-admin, please rerender

**Comment by giswqs** [comment]
@jsignell All checks have passed. You can review it now.

**Review by jsignell — APPROVED** [review]
:rocket:

**Comment by AndrewAnnex** [comment]
@jsignell @giswqs any chance we could merge this? I had opened https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4696 but didn't check this repo first to see this pr

**Comment by jsignell** [comment]
Fine by me!

**Pull request merged**
